name: Docker

on:
    workflow_dispatch:

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v2
            with:
              ref: master
          - name: ZAPScan
            uses: zaproxy/action-full-scan@v0.2.0
            with:
              token: ${{ secrets.GITHUB_TOKEN }}
              docker_name: 'owasp/zap2docker-stable'
              target: 'https://reancare-api-dev.services.reanfoundation.org:8282'
              cmd_options: '-a'
          - name: upload ZAP scan SARIF report
            uses: github/codeql-action/upload-sarif@v1
            with:
              sarif_file: ${{ steps.ZAPScan.outputs.sarif }}