name: dump

on:
  workflow_dispatch:

jobs:
  dump:
    runs-on: ubuntu-latest
    steps:
      # - run: echo ${{github.ref}}
      # - run: echo running on branch ${GITHUB_REF##*/}
      - name: Get the current branch name
        shell: bash
        run: echo "Branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
        id: myref
      - name: Dump context
        if: ${{ env.Branch == 'develop_cicd' }}
        run: |
          echo ${{ steps.myref.outputs.branch }}
          echo "Wrong branch"
          exit 1 // added failure
      - name: Show context
        run: |
          echo "${{ github.actor }}"
      # - name: the dump
      #   uses: crazy-max/ghaction-dump-context@v1