name: dump

on:
  workflow_dispatch:

jobs:
  dump:
    runs-on: ubuntu-latest
    steps:
      - name: Dump context
        if: ${GITHUB_REF#refs/heads/} == 'master'
        run: |
          echo ${GITHUB_REF#refs/heads/}
          echo Wrong branch
          exit 1 // added failure
      - name: Show context
        run: |
          echo "${{ github.actor }}"
      # - name: the dump
      #   uses: crazy-max/ghaction-dump-context@v1